version: '3'

services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_DB=employee_manager
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/employee_manager
    command: ["python", "manage.py",  "runserver", "0.0.0.0:8000"]