version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=employee_manager
      - POSTGRES_USER=employee_manager
      - POSTGRES_DB=employee_manager
    volumes:
    - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://employee_manager:employee_manager@db:5432/employee_manager
    command: ["python", "manage.py",  "runserver", "0.0.0.0:8000"]

volumes:
  postgres_data:
