version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build and up containers
          command: docker-compose up -d
  test:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose run web sh -c "pytest -v -rf --junitxml=test-results/junit.xml --cov=core/ --cov-report html:test-results/coverage/html --cov-report xml:test-results/coverage/coverage.xml --cov-report term-missing"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - run:
          name: Send Coverage status
          command: docker-compose run -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" web sh -c "pipenv install --dev --skip-lock --system && coveralls"
  deploy:
    docker:
      - image: buildpack-deps:xenial-scm
    steps:
      - checkout
      - run:
          name: Log in to Heroku
          command: bash .circleci/login-heroku.sh
      - run:
          name: Deploy App
          command: bash .circleci/deploy-heroku.sh
      - run:
          name: Run migrations
          command: |
            source .circleci/setup-env.sh
            heroku run python manage.py migrate --remote $HEROKU_REMOTE

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold_for_approval:
          type: approval
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
                - develop