version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: build and up containers
          command: docker-compose up -d
      - run:
          name: install dependencies
          command: docker-compose exec web sh -c "pipenv install --dev --skip-lock --system"
      - run:
          name: run tests
          command: docker-compose exec web sh -c "pytest -v -rf --junitxml=test-results/junit.xml"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-reports
          destination: test-reports
workflows:
  version: 2
  build_and_test:
    jobs:
      - build